---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argo-cd-cert-ui
spec:
  secretName: argocd-server-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: argocd.opendesk.raynet.de
  dnsNames:
  - argocd.opendesk.raynet.de
...