---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argo-cd-cert-ui
spec:
  secretName: argocd-server-tls
  issuerRef:
    name: hetzner-prod-issuer
    kind: ClusterIssuer
  commonName: argocd.sts34.de
  dnsNames:
  - argocd.sts34.de
...