apiVersion: v1
data:
  application.instanceLabelKey: argocd.argoproj.io/instance
  resource.exclusions: |
    - apiGroups:
      - cilium.io
      kinds:
      - CiliumIdentity
      clusters:
      - "*"
kind: ConfigMap
metadata:
  name: argocd-cm