apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  namespace: monitoring
  labels:
    dashboards: "grafana"
spec:
  version: 11.5.2
  ingress:
    metadata:
      annotations:
        cert-manager.io/cluster-issuer: hetzner-prod-issuer
    spec:
      ingressClassName: nginx
      rules:
        - host: grafana.sts34.de
          http:
            paths:
              - backend:
                  service:
                    name: grafana-service
                    port:
                      number: 3000
                path: /
                pathType: Prefix
      tls:
        - hosts:
            - grafana.sts34.de
          secretName: grafana.sts34.de-tls
  config:
    log:
      mode: "console"
    metrics:
      enabled: "true"