apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: elastic-system

resources:
- base/namespace.yaml
- https://download.elastic.co/downloads/eck/2.16.0/crds.yaml
- https://download.elastic.co/downloads/eck/2.16.0/operator.yaml
