---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elastic-system
  namespace: argocd
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  project: default
  source:
    chart: eck-operator
    repoURL: https://helm.elastic.co
    targetRevision: v2.16.0
    helm:
      values: |
        managedNamespaces: []
        
        createClusterScopedResources: true
        
        webhook:
          enabled: true   
  destination:
    server: https://kubernetes.default.svc
    namespace: elastic-system