apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elastic-system
  namespace: argocd
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true
spec:
  destination:
    namespace: elastic-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: elastic-system
    repoURL: https://github.com/cgruenwald/kube.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ServerSideApply=true