apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  project: default
  sources:
    - chart: ingress-nginx
      repoURL: https://kubernetes.github.io/ingress-nginx
      targetRevision: v4.11.x
      helm:
        values: |
          controller:
            externalTrafficPolicy: "Local"
            hostNetwork: true
            allowSnippetAnnotations: "true"
            extraArgs:
              enable-ssl-passthrough: "true"
            ingressClassResource:
              default: true
            kind: DaemonSet
            metrics:
              enabled: true
              port: 10254
              portName: metrics
              service:
                annotations:
                  prometheus.io/port: "10254"
                  prometheus.io/scrape: "true"
              serviceMonitor:
                enabled: true
                additionalLabels:
                  release: prometheus
                scrapeInterval: 10s
            service:
              watchIngressWithoutClass: "true"
          defaultBackend:
            enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx


