apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
  project: default
  sources:
    - chart: ingress-nginx
      repoURL: https://kubernetes.github.io/ingress-nginx
      targetRevision: v4.x.x
      helm:
        values: |
          controller:
            metrics:
              port: 10254
              portName: metrics
              enabled: true
              service:
                annotations:
                  prometheus.io/scrape: "true"
                  prometheus.io/port: "10254"
            allowSnippetAnnotations: "true"
            extraArgs:
              enable-ssl-passthrough: "true"
            kind: Deployment
            watchIngressWithoutClass: "true"
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx


