apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
spec:
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
  project: default
  sources:
    - chart: minio
      repoURL: https://charts.bitnami.com/bitnami
      targetRevision: "14.10.x"
      helm:
        values: |
          auth:
            existingSecret: "minio-secret"
            rootUserSecretKey: "user"
            rootPasswordSecretKey: "password"
          ingress:
            enabled: true
            ingressClassName: "nginx"
            hostname: minio.sts34.de
            annotations:
              cert-manager.io/cluster-issuer: "hetzner-prod-issuer"
            tls: true
          apiIngress:
            enabled: true
            ingressClassName: "nginx"
            hostname: minio-api.sts34.de
            annotations:
              cert-manager.io/cluster-issuer: "hetzner-prod-issuer"
            tls: true
          persistence:
            storageClass: "directpv-min-io"
            size: 10Gi
          metrics:
            enabled: true
            serviceMonitor:
              enabled: true
              labels:
                release: kube-prom
            prometheusRule:
              enabled: true
              additionalLabels:
                release: kube-prom
  destination:
    server: https://kubernetes.default.svc
    namespace: minio


