apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  project: default
  sources:
    - chart: minio
      repoURL: registry-1.docker.io/bitnamicharts
      targetRevision: 14.x.x
      helm:
        values: |
          podAnnotations:
            prometheus.io/scrape: "true"
            prometheus.io/path: "/minio/v2/metrics/cluster"
            prometheus.io/port: "9000"
          global:
            defaultStorageClass: "directpv-min-io"
          mode: distributed
          statefulset:
            replicaCount: 4
            drivesPerNode: 2
          auth:
            existingSecret: "minio-secret"
            rootUserSecretKey: "user"
            rootPasswordSecretKey: "password"
          ingress:
            enabled: true
            ingressClassName: "nginx"
            hostname: minio.sts34.de
            annotations:
              cert-manager.io/cluster-issuer: "hetzner-prod-issuer"
            tls: true
          apiIngress:
            enabled: true
            ingressClassName: "nginx"
            hostname: minio-api.sts34.de
            annotations:
              cert-manager.io/cluster-issuer: "hetzner-prod-issuer"
            tls: true
          persistence:
            storageClass: "directpv-min-io"
            size: 10Gi
          resources:
            requests:
              cpu: 250m
              ephemeral-storage: 50Mi
              memory: 256Mi
            limits:
              cpu: 1000m
              ephemeral-storage: 4Gi
              memory: 2048Mi
          metrics:
            enabled: true
            serviceMonitor:
              enabled: true
              labels:
                release: prometheus
            prometheusRule:
              enabled: true
              additionalLabels:
                release: prometheus
  destination:
    server: https://kubernetes.default.svc
    namespace: minio


