apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: grafana-db
  namespace: monitoring
spec:
  instances: 3
  storage:
    size: 19Gi
    storageClass: directpv-min-io
  monitoring:
    enablePodMonitor: true
  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname
    podAntiAffinityType: required
  backup:
    barmanObjectStore:
      wal:
        compression: gzip
        encryption: AES256
      destinationPath: s3://grafana-backup/
      endpointURL: https://minio-api.sts34.de
      s3Credentials:
        accessKeyId:
          name: minio-creds
          key: MINIO_ACCESS_KEY
        secretAccessKey:
          name: minio-creds
          key: MINIO_SECRET_KEY