---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: nextcloud-db
  namespace: nextcloud
spec:
  instances: 3
  storage:
    size: 20Gi
    storageClass: directpv-min-io
  monitoring:
    enablePodMonitor: true
  enableSuperuserAccess: true
  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname
    podAntiAffinityType: required
  backup:
    barmanObjectStore:
      wal:
        compression: gzip
        encryption: AES256
      destinationPath: s3://nextcloud-backup/
      endpointURL: http://minio.minio.svc:9000
      s3Credentials:
        accessKeyId:
          name: minio-creds
          key: MINIO_ACCESS_KEY
        secretAccessKey:
          name: minio-creds
          key: MINIO_SECRET_KEY