apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-secret
  namespace: nextcloud
type: Opaque
stringData:
  host: http://minio.minio.svc.cluster.local:9000
  accessKey: qO3yl1rVpFZkEGa1bAwW
  secretKey: h4daQ1JdRV6uxs7Y7YJniOFvL0ml6dwRmDeS2dTe
  bucket: nextcloud
  sse_c_key: ""
