apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
# - base/argo-cd-cmp-helmfile-cm.yaml
- base/argo-cd-namespace.yaml
# - base/argo-cd-certificate.yaml
# - base/argo-cd-ui-ingress.yaml
# - base/argo-cd-servicemonitors.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.13.3/manifests/install.yaml


# patches:
# - path: overlays/argo-cd-cm.yaml
# - path: overlays/argocd-cmd-params-cm.yaml
# - path: overlays/sidecar-plugin.yaml
#   target:
#     kind: Deployment
#     name: argocd-repo-server
# 
# - path: overlays/argo-cd-networkpolicy.yaml
#   target:
#     kind: NetworkPolicy
#     name: argocd-redis-ha-proxy-network-policy
# 
# - path: overlays/argo-cd-networkpolicy2.yaml
#   target:
#     kind: NetworkPolicy
#     name: argocd-redis-ha-server-network-policy